name: CI
on:
  workflow_dispatch:
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: calculation
        id: cal
        run: echo "Name=madhan" >> $GITHUB_RANDOM
      - name: output
        run: echo "${{steps.cal.outputs.GITHUB_RANDOM}}"